[project]
name = 'Digital-Identity-for-Refugee-Education-Records'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.academic-history]
path = 'contracts/academic-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.credential-verification]
path = 'contracts/credential-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.school-placement]
path = 'contracts/school-placement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
